spring:
  security:
    oauth2:
      client:
        provider: #???, ???? ?? provider? ??????.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          google:
            clientId: 796340878442-c5ndt5n5kntlvmkl1mgpba69amtaaahs.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: http://ez304.iptime.org:8003/login/oauth2/code/google
            scope:
              - email
              - profile

          naver:
            clientId: Jd_CniKiWJqxM4v7qH1w
            client-secret: numUr9t6pN
            redirect-uri: http://ez304.iptime.org:8003/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            clientId: 0238245bbb90e2966bfb79025001f6b7
            client-secret: WPAGrX5zFnKhkYcAnqWFXwdHbIm0B1B7
            redirect-uri: http://ez304.iptime.org:8003/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
            client-authentication-method: POST